CREATE DATABASE etimUsuario;

USE usuario;
CREATE TABLE etimUsuario(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR (255) NOT NULL
);

